apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql-flights
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
